rbr="source ~/.bashrc"
dcu="docker-compose up -d"
dcrp="docker-compose run -d --service-ports postgres"
sdn="shutdown now"
alias ac="evince "
alias eb="cd ~/Desktop/Parallels\ Shared\ Folders/Home/Documents/Ebooks && o ."
alias o="nautilus"
alias sdn="shutdown now"
